package com.ml.hibernate.enums;

public enum Subject {

	HINDI, ENGLISH, MATHEMATICS, SCIENCE, COMPUTER, GEOGRAPHY, HISTORY, POLITY, ECONOMY, STATISTICS, MECHANICS, PHYSICS,
	CHEMISTRY, BIOLOGY, SANSKRIT, URDU, ART, SPORTS;
}
